spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
#    password: newpass
#    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
    password: 123456
#    url: jdbc:mysql://10.0.0.57/sell?characterEncoding=utf-8&useSSL=false
#    password: 123456
    url: jdbc:mysql://192.168.1.119/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: wx668678456aca2b35
  mpAppSecret: c23e0a3af787b7fb3e79cffaa4643c8a