spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
#    password: newpass
#    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&useSSL=false
    password: 123456
#    url: jdbc:mysql://10.0.0.27/sell?characterEncoding=utf-8&useSSL=false
#    password: 123456
    url: jdbc:mysql://192.168.1.119/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.1.119
    port: 6379
    password:

server:
  servlet:
    context-path: /sell

wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: c23e0a3af787b7fb3e79cffaa4643c8a
  payAppId: dddd
  payAppSecret: dddd
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: /Users/wenqi/Downloads/cert/h5.p12
  notifyUrl: http://wake.nat100.top/sell/pay/wechat/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  weChatMpAuthorize: http://wake.nat100.top
  wxChatOpenAuthorize: http://wake.nat100.top
  sell: http://wake.nat100.top